os: linux
language: python
python: 3.6
install:
   - ./startup.sh --no-startup
   - pip install pytest
   - pip install pytest-cov
   - pip install coveralls
   - npm install -g markdownlint-cli
script:
   - pytest tests/server_tests/ --cov=tabpy-server/tabpy_server
   - pytest tests/tools_tests/ --cov=tabpy-tools/tabpy_tools --cov-append
   - markdownlint .
after_success:
   - coveralls
